language: php
sudo: false

php:
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4

matrix:
  allow_failures:
    - php: 7.1
  fast_finish: true

before_script:
  - composer install

script:
  - ./vendor/bin/phpunit --exclude-group online
